# Generated by Django 4.0.1 on 2022-09-26 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=80)),
                ('Password', models.CharField(max_length=80)),
                ('User_ID', models.CharField(max_length=80)),
                ('Age_group_ID', models.CharField(max_length=80)),
                ('User_type', models.CharField(max_length=80)),
            ],
        ),
    ]
