# Generated by Django 4.0.1 on 2022-10-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Headline', models.CharField(max_length=80)),
                ('Contenttypes', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='User_ID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='User_type',
        ),
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='Age_group_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
