# Generated by Django 4.0.1 on 2022-11-08 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_remove_user_user_id_remove_user_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agegroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age_group', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genre_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mail',
            new_name='Mail',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Contenttypes',
        ),
        migrations.AddField(
            model_name='article',
            name='Content',
            field=models.TextField(default='Error Content Missing'),
        ),
        migrations.AddField(
            model_name='article',
            name='Date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_read', models.DateTimeField(auto_now_add=True, null=True)),
                ('Age_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.agegroup')),
                ('Article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
                ('Genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.genres')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='GenreID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.genres'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Age_group_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.agegroup'),
        ),
    ]
