# Generated by Django 4.0.1 on 2022-11-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_age_group_id_user_age_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agegroup',
            old_name='Age_group',
            new_name='age_group',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Date_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='GenreID',
            new_name='genreID',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Headline',
            new_name='headline',
        ),
        migrations.RenameField(
            model_name='genres',
            old_name='Genre_name',
            new_name='genre_name',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='Age_group',
            new_name='age_group',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='Article',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='Date_read',
            new_name='date_read',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Age_group',
            new_name='age_group',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Mail',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='username',
        ),
    ]
