# Generated by Django 4.0.1 on 2022-11-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_age_group_agegroup_age_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='genreID',
            new_name='genre',
        ),
    ]
